config/routes.rb
Rails.application.routes.draw do
  get 'auth/login'

  get 'auth/dropbox_callback'

  get 'auth/logout'

  root 'static#home'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  require 'dropbox_sdk'

  def login
    authorize_url = dropbox_auth.start()
    redirect_to authorize_url
  end

  def dropbox_callback
    access_token, user_id, url_state = dropbox_auth.finish(params)
    session[:access_token] = access_token
    user = DropboxClient.new(access_token).account_info
    validate_user user
    redirect_to root_path
  end

  def logout
    session.delete(:current_user)
    redirect_to root_path
  end

  private

  def validate_user user
    existing_user = User.find_by(email: user["email"])
    if existing_user.present?
      session[:current_user] = existing_user.name
    else
      new_user = User.create(name: user["display_name"], dropbox_uid: user["uid"], email: user["email"], dropbox_token: session[:access_token])
      session[:current_user] = new_user.name
    end
  end

  def dropbox_auth
   redirect_uri = url_for :controller => 'auth', :action => 'dropbox_callback'
   DropboxOAuth2Flow.new(ENV['APP_KEY'], ENV['APP_SECRET'], redirect_uri, session, :dropbox_auth_csrf_token)
 end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if session[:current_user].present? %>
          <li><a href="#">Hello, <%= session[:current_user] %></a></li>
          <li><%= link_to 'Logout', auth_logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', auth_login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DropboxAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/navbar' %>

<%= yield %>

</body>
</html>